const presets = [
  {
    id: "default",
    label: "Default (keep current settings)",
    description: "Create a blank project without changing app settings or channels.",
    defaultName: "New Project",
    defaultTopic: "",
    defaultSchedule: "",
    projectOverrides: {},
    resetDefaults: false,
    resetChannels: false,
  },
  {
    id: "reset-defaults",
    label: "Fresh start (clears channels)",
    description: "Reset the app to default settings and remove all existing channels for a clean workspace.",
    defaultName: "Fresh Project",
    defaultTopic: "",
    defaultSchedule: "",
    projectOverrides: { multi_language: false, multi_style: false, styles: [] },
    resetDefaults: true,
    resetChannels: true,
    defaults: {
      theme: "obsidian",
      ffmpeg_path: "ffmpeg",
      ffprobe_path: "ffprobe",
    }
  },
  {
    id: "biblical-multilingual",
    label: "Biblical Multilingual Series",
    description: "A multilingual Bible project with uplifting styles and recurring themes.",
    defaultName: "Biblical Multilingual",
    defaultTopic: "Scripture set to music",
    defaultSchedule: "weekly",
    projectOverrides: {
      multi_language: true,
      multi_style: true,
      languages: ["English", "Spanish", "Portuguese"],
      styles: ["ethereal", "radiant", "choir"],
    },
    resetDefaults: false,
    resetChannels: false,
  },
  {
    id: "youtube-short-campaign",
    label: "YouTube Shorts Campaign",
    description: "Fast-turnaround shorts with upbeat hooks and daily upload cadence.",
    defaultName: "Shorts Campaign",
    defaultTopic: "Short-form music video series",
    defaultSchedule: "daily",
    projectOverrides: {
      multi_language: false,
      multi_style: true,
      styles: ["uplifting", "bright"],
    },
    resetDefaults: false,
    resetChannels: false,
  },
  {
    id: "brand-launch",
    label: "Brand Launch Flow",
    description: "A premium launch template for a branded album or channel rollout.",
    defaultName: "Brand Launch",
    defaultTopic: "Launch campaign",
    defaultSchedule: "biweekly",
    projectOverrides: {
      multi_language: false,
      multi_style: true,
      styles: ["cinematic", "ambient"],
      languages: ["English"],
    },
    resetDefaults: false,
    resetChannels: false,
  },
  {
    id: "global-choir-series",
    label: "Global Choir Series",
    description: "A multi-language choral series for worship, community, and celebration.",
    defaultName: "Global Choir Series",
    defaultTopic: "Community worship arrangements",
    defaultSchedule: "weekly",
    projectOverrides: {
      multi_language: true,
      multi_style: true,
      languages: ["English", "French", "German"],
      styles: ["choir", "ambient", "uplifting"],
    },
    resetDefaults: false,
    resetChannels: false,
  }
];

export default presets;
