#!/usr/bin/env python3
"""Bundle the riffusion source package into the notebook that actually gets pushed.

Kaggle notebooks are pushed as a *single file*: `settings.rs` `include_str!`s
`src-tauri/kaggle_notebooks/riffusion.ipynb` and writes it as `setup_and_serve.ipynb`, and nothing
else travels with it. The notebook's "Step 3: Setup Source Package" cell nevertheless did
`sys.path.insert(0, '/kaggle/working/kaggle_riffusion/notebook/src')` and imported from it — a
directory that only ever existed on a developer's machine. On Kaggle it aborted the run with
`ModuleNotFoundError: No module named 'preset_engine'`, which is what a user sees as "Error" a few
seconds into a boot that looked healthy.

heartmula does not have this problem because it clones its source from a git repo at runtime. That
is a fine answer for a published library and a bad one here: these seven modules live in this repo,
change with it, and would need a second repo and a push-before-you-test workflow to stay in sync.

So they are embedded instead — base64 into a setup cell that writes the tree out before importing
anything. Base64 rather than inline source because these files contain triple quotes, backslashes
and f-strings, and every one of those is a way for naive quoting to produce a notebook that is
syntactically valid and subtly wrong.

The second bug this fixes: the modules import each other *relatively* (`from .song_arranger import
...`), which only works if they are imported as a package. The old cell put `src/` itself on the
path and imported `api_server` as a top-level module, so even with the files present the very next
line would have raised "attempted relative import with no known parent package". The generated cell
puts the *parent* on the path and imports `src.api_server`, so `src/__init__.py` does its job.

    python3 scripts/build-riffusion-notebook.py          # regenerate
    python3 scripts/build-riffusion-notebook.py --check  # verify it is current (CI)

Re-run this whenever anything under scripts/kaggle_riffusion/notebook/ changes.
"""

import argparse
import base64
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "scripts" / "kaggle_riffusion" / "notebook"
TARGET = ROOT / "src-tauri" / "kaggle_notebooks" / "riffusion.ipynb"

# Where the notebook unpacks itself. Must match what the modules expect: preset_engine resolves
# styles.yaml as Path(__file__).parent.parent / "presets" / "styles.yaml", so `presets/` has to sit
# beside `src/`, not inside it.
NOTEBOOK_DIR = "/kaggle/working/kaggle_riffusion/notebook"

# Everything the run needs, relative to SOURCE.
BUNDLED = ["src/__init__.py", "src/api_server.py", "src/audio_stitcher.py", "src/job_queue.py",
           "src/long_form_generator.py", "src/preset_engine.py", "src/song_arranger.py",
           "src/tunnel_manager.py", "src/utils.py", "presets/styles.yaml"]

MARKER = "# ── generated by scripts/build-riffusion-notebook.py ──"


def build_setup_cell() -> list[str]:
    """The cell that writes the source tree out, then imports it as a package."""
    payload = {}
    for rel in BUNDLED:
        path = SOURCE / rel
        if not path.is_file():
            sys.exit(f"missing bundled file: {path}")
        payload[rel] = base64.b64encode(path.read_bytes()).decode("ascii")

    # One base64 blob per file, wrapped so the notebook stays readable in Kaggle's editor.
    lines = [
        MARKER + "\n",
        "# Regenerate with: python3 scripts/build-riffusion-notebook.py\n",
        "#\n",
        "# The source package is embedded because a Kaggle push carries exactly one file. Writing it\n",
        "# out here is what makes `import src.api_server` below work at all.\n",
        "import base64, os, pathlib, sys\n",
        "\n",
        f"NOTEBOOK_DIR = {NOTEBOOK_DIR!r}\n",
        "\n",
        "_BUNDLE = {\n",
    ]
    for rel, b64 in payload.items():
        lines.append(f"    {rel!r}: (\n")
        for i in range(0, len(b64), 96):
            lines.append(f"        {b64[i:i + 96]!r}\n")
        lines.append("    ),\n")
    lines += [
        "}\n",
        "\n",
        "for _rel, _b64 in _BUNDLE.items():\n",
        "    _dest = pathlib.Path(NOTEBOOK_DIR) / _rel\n",
        "    _dest.parent.mkdir(parents=True, exist_ok=True)\n",
        "    _dest.write_bytes(base64.b64decode(''.join(_b64) if isinstance(_b64, tuple) else _b64))\n",
        "\n",
        "# The *parent* goes on the path, not src/ itself: the modules import each other relatively\n",
        "# (`from .song_arranger import ...`), which needs them to be a package rather than a set of\n",
        "# top-level modules. src/__init__.py makes `src` that package.\n",
        "if NOTEBOOK_DIR not in sys.path:\n",
        "    sys.path.insert(0, NOTEBOOK_DIR)\n",
        "\n",
        "from src.preset_engine import PresetEngine\n",
        "from src.song_arranger import SongArranger\n",
        "from src.long_form_generator import LongFormGenerator\n",
        "from src.audio_stitcher import stitch_song_sections\n",
        "from src.api_server import app\n",
        "from src.tunnel_manager import TunnelManager\n",
        "\n",
        "print(f'✅ Source package written to {NOTEBOOK_DIR} and imported')\n",
        "print(f'   Available presets: {PresetEngine().list_presets()}')\n",
    ]
    return lines


def rewrite_cell(source: list[str]) -> list[str]:
    """Point the remaining cells at the package, not at bare top-level modules."""
    out = []
    for line in source:
        # uvicorn resolves this string itself, so it needs the package path too — a detail easy to
        # miss because it looks like data rather than an import.
        line = line.replace('"api_server:app"', '"src.api_server:app"')
        line = line.replace("'api_server:app'", "'src.api_server:app'")
        for mod in ("preset_engine", "song_arranger", "long_form_generator", "audio_stitcher",
                    "api_server", "tunnel_manager", "job_queue", "utils"):
            line = line.replace(f"from {mod} import ", f"from src.{mod} import ")
        out.append(line)
    return out


def generate() -> str:
    nb = json.loads(TARGET.read_text(encoding="utf-8"))
    setup_done = False
    for cell in nb["cells"]:
        if cell.get("cell_type") != "code":
            continue
        src = "".join(cell.get("source", []))
        # The setup cell is the one that puts SRC_DIR on the path, or the one this script wrote last
        # time. Matching on either keeps the script idempotent.
        if MARKER in src or ("sys.path.insert" in src and "SRC_DIR" in src):
            cell["source"] = build_setup_cell()
            cell["outputs"] = []
            cell["execution_count"] = None
            setup_done = True
        else:
            cell["source"] = rewrite_cell(cell.get("source", []))
    if not setup_done:
        sys.exit("could not find the source-setup cell in riffusion.ipynb")
    return json.dumps(nb, indent=1, ensure_ascii=False) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="fail if the notebook is out of date instead of rewriting it")
    args = ap.parse_args()

    built = generate()
    current = TARGET.read_text(encoding="utf-8")
    if args.check:
        if built != current:
            sys.exit("riffusion.ipynb is stale — run: python3 scripts/build-riffusion-notebook.py")
        print("riffusion.ipynb is up to date")
        return
    TARGET.write_text(built, encoding="utf-8")
    kb = len(built) / 1024
    print(f"wrote {TARGET.relative_to(ROOT)} ({kb:.0f} KB, {len(BUNDLED)} files embedded)")


if __name__ == "__main__":
    main()
