#!/usr/bin/env bash
# Reclaim build scratch, keeping the version that is currently installed.
#
# Every release cycle leaves behind a ~100 MB .deb, its ~110 MB extracted tree, and a ~300 MB
# AppImage AppDir. On a machine that runs at 90%+ full that is two or three builds of headroom, and
# the failure mode is a build dying half-way through bundling with "No space left on device" — after
# twenty minutes of compiling.
#
# Everything removed here is regenerated by the next `npm run tauri -- build`. The installed
# application is untouched: it lives in /usr, not in target/.
#
#   bash scripts/prune-build-artifacts.sh            # prune, keep the installed version's deb
#   bash scripts/prune-build-artifacts.sh --all      # prune every bundle, including that one
set -euo pipefail

cd "$(dirname "$0")/.."
BUNDLE="src-tauri/target/release/bundle"
KEEP="$(dpkg-query -W -f='${Version}' ai-music-video-studio 2>/dev/null || true)"
[ "${1:-}" = "--all" ] && KEEP=""

before=$(df --output=avail -BM / | tail -1 | tr -dc '0-9')

if [ -d "$BUNDLE/deb" ]; then
  for entry in "$BUNDLE"/deb/*; do
    [ -e "$entry" ] || continue
    if [ -n "$KEEP" ] && [[ "$(basename "$entry")" == *"_${KEEP}_"* ]]; then
      echo "keep   $(basename "$entry")"
      continue
    fi
    echo "remove $(basename "$entry")"
    rm -rf "$entry"
  done
fi

# The AppDir is a staging tree rebuilt from scratch every time, and the AppImage is not what gets
# installed here — both are pure scratch on this machine.
rm -rf "$BUNDLE/appimage/"*.AppDir "$BUNDLE"/appimage/*.AppImage 2>/dev/null || true

# Downloaded crate sources and the npm/npx caches all re-fetch on demand.
rm -rf ~/.cargo/registry/src ~/.cargo/registry/cache ~/.npm/_cacache ~/.npm/_npx 2>/dev/null || true

after=$(df --output=avail -BM / | tail -1 | tr -dc '0-9')
echo "freed $(( after - before )) MB — ${after} MB now available"
